= Software Engineering Lab - Infrastructure

This repository contains a few projects to ease developing and building the Java projects for the Software Engineering Labs at TU Dresden.

== Parent

The kickstart project refers to a parent project that contains Maven configuration for an advanced build to be executed in a continuous integration environment.
Here are the additional steps that will be executed if the build is run with the `ci` profile enabled (`mvn clean install -Pci`).

* the JavaDoc of the project is build, packaged and attached to the project
* the reference documentation (i.e. all `….adoc` files in `src/main/asciidoc`) will be rendered into HTML and PDF
* both JavaDoc and reference documentation are packaged into a zip and attached to the produced artifacts
* JaCoCo report for unit test code coverage is generated

== Resources

The `resources` module contains the assembly descriptor to package Javadoc and reference documentation via the assembly plugin declared in the parent project.

== Releases

```
$ mvn release:prepare \
-DscmReleaseCommitComment="$ticketId - Release version $version." \
-DscmDevelopmentCommitComment="$ticketId - Prepare next development iteration."
Edit commit messages to follow the usual pattern.
$ mvn release:perform
```
